<?php require('template/header.phtml') ?>

<div class="container mt-5">
    <br/>
    <?php if (!empty($view->bookingDetails)): ?>
    

    <!--adding a floating image div to the right of the contaner-->
    <div class="float-image">
        <img src="<?= htmlspecialchars($view->bookingDetails['charge_point_picture_url']); ?>" alt="Booking Image" class="img-fluid">
    </div>

        <h1>Booking Details</h1>
        <div class="paragraph-container">
        <h4>Booking ID: <?= htmlspecialchars($view->bookingDetails['booking_id']); ?></h4>
        <!--print the values of the booking details-->

                        <?php 
                        // Define status text and classes
                        $statusText = '';
                        $statusClass = '';
                        switch ($view->bookingDetails['booking_status_id']) {
                            case 1:
                                $statusText = 'Pending Approval';
                                $statusClass = 'details-pending';
                                break;
                            case 2:
                                $statusText = 'Approved';
                                $statusClass = 'details-approved';
                                break;
                            case 3:
                                $statusText = 'Rejected';
                                $statusClass = 'details-declined';
                                break;
                            default:
                                $statusText = 'Unknown';
                                $statusClass = '';
                        }
                        ?>

        <p>Booking Status: <span class="<?= $statusClass; ?>" > <?= htmlspecialchars($statusText); ?></span></p>
        <p>Booking Date: <?= htmlspecialchars(explode(' ', $view->bookingDetails['booking_date'])[0]); ?></p>
        <p>Booking Time: <?= htmlspecialchars($view->bookingDetails['booking_time']); ?></p>
        </div>
        <!--print charge point details-->

        <br/><br/>
        <h1>Charge Point Details</h1>
        <div class="paragraph-container">
        <p>Charge Point ID: <?= htmlspecialchars($view->bookingDetails['charge_point_id']); ?></p>
        <p>Street Name: <?= htmlspecialchars($view->bookingDetails['streetName']); ?></p>
        <p>House Number: <?= htmlspecialchars($view->bookingDetails['house_number']); ?></p>
        <p>Road: <?= htmlspecialchars($view->bookingDetails['road']); ?></p>
        <p>Block: <?= htmlspecialchars($view->bookingDetails['block']); ?></p>
        <p>City: <?= htmlspecialchars($view->bookingDetails['city_name']); ?></p>
        <p>Post Code: <?= htmlspecialchars($view->bookingDetails['postcode']); ?></p>
        <p>Price per kWh: <?= htmlspecialchars($view->bookingDetails['price_per_kwh']); ?></p>
        </div>

        <br/><br/>
        <h1>Charge Point Owner Details</h1>
        <div class="paragraph-container">
        <p>Homeowner Name: <?= htmlspecialchars($view->bookingDetails['ownerfirst_name'] . ' ' . $view->bookingDetails['ownerlast_name']); ?></p>
        <p>Homeowner Phone: <?= htmlspecialchars($view->bookingDetails['homeowner_phone']); ?></p>
        </div>

    <?php else: ?>
        <p>No booking records found.</p>

    <?php endif; ?>

</div>
    <br/>
    <div class="container">
        <a href="booking-history.php" class="btn btn-primary">Back to Booking History</a>
    </div>
    <br/>


<?php require('template/footer.phtml') ?>