<?php require_once('template/header.phtml'); ?>

<div class="container mt-5">
    <br/>
    <?php if (!empty($view->bookings)): ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Charge Point</th>
                <th>Booking Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($view->bookings as $booking): ?>
                    <tr>
                        <td><?= htmlspecialchars($booking['streetName'] . ' ' . $booking['house_number']); ?></td>
                        <td><?= htmlspecialchars(explode(' ', $booking['booking_date'])[0]); ?></td>
                        <td><?= htmlspecialchars($booking['booking_time']); ?></td>
                        
                        <?php 
                        // Define status text and classes
                        $statusText = '';
                        $statusClass = '';
                        switch ($booking['booking_status_id']) {
                            case 1:
                                $statusText = 'Pending Approval';
                                $statusClass = 'details-pending';
                                break;
                            case 2:
                                $statusText = 'Approved';
                                $statusClass = 'details-approved';
                                break;
                            case 3:
                                $statusText = 'Rejected';
                                $statusClass = 'details-declined';
                                break;
                            default:
                                $statusText = 'Unknown';
                                $statusClass = '';
                        }
                        ?>

                        <td ><span class="<?= $statusClass; ?>"><?= htmlspecialchars($statusText); ?></span></td>
                        <td><a href="booking-details.php?booking_id=<?= $booking['booking_id']; ?>" class="btn btn-info">View Details</a></td>
                    </tr>
                <?php endforeach; ?>

            
        </tbody>
    </table>
    <?php else: ?>
        <p>No booking records found.</p>
    <?php endif; ?>
</div>


<?php require_once('template/footer.phtml'); 