<!-- FOOTER -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-info">
                    <div class="section-title">
                        <h2>Contact Info</h2>
                    </div>
                    <address>
                        <p>Phone: 36XXX626</p>
                        <p>Email: <a href="mailto:BorrowMyCharger@example.com">BorrowMyCharger@example.com</a></p>
                    </address>
                    <div class="copyright-text"> 
                        <p>&copy; All Rights Reserved to Borrow My Charger</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
