<!-- FOOTER -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-info">
                    <div class="section-title">
                        <h2>Contact Info</h2>
                    </div>
                    <address>
                        <p>Phone: 36XXX626</p>
                        <p>Email: <a href="mailto:BorrowMyCharger@example.com">BorrowMyCharger@example.com</a></p>
                    </address>
                    <div class="copyright-text"> 
                        <p>&copy; All Rights Reserved to Borrow My Charger</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


     <!-- SCRIPTS -->
     <script src="js/jquery.js"></script>
     <script src="js/bootstrap.min.js"></script>
     <script src="js/owl.carousel.min.js"></script>
     <script src="js/smoothscroll.js"></script>
     <script src="js/custom.js"></script>

</body>
</html>
