<!-- FOOTER -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-info">
                    <div class="section-title">
                        <h2>Contact Info</h2>
                    </div>
                    <address>
                        <p>Phone: +973 17777777</p>
                        <p>Email: <a href="mailto:contact@borrowmycharger.com">contact@borrowmycharger.com</a></p>
                    </address>
                    <div class="copyright-text"> 
                        <p>&copy; All Rights Reserved to Borrow My Charger</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- BACK TO TOP BUTTON -->
<button id="backToTop" style="display: none; position: fixed; bottom: 20px; right: 20px; z-index: 1000; padding: 10px; background-color: #B68942; color: white; border: none; border-radius: 5px; cursor: pointer;">
    &#8593; <!-- Arrow up character -->
</button>



<script>
    // Show the button when scrolling down
    $(window).scroll(function() {
        if ($(this).scrollTop() > 100) {
            $('#backToTop').fadeIn();
        } else {
            $('#backToTop').fadeOut();
        }
    });

    // Scroll to top on button click
    $('#backToTop').click(function() {
        $('html, body').animate({ scrollTop: 0 }, 800);
        return false;
    });
</script>

</body>
</html>